### ISSUE TITLE
System.IO.DirectoryNotFoundException for some characters in project path

### ISSUE THREAD

**Issue by lxymahatma** [Kir-Antipov/HotAvalonia#1]
My project path contains "C#" and get converted to "C%23" so the program throws the System.IO.DirectoryNotFoundException
![image](https://github.com/Kir-Antipov/HotAvalonia/assets/66151783/bd61a8f3-6663-464d-898c-66f451864400)

**Comment by Kir-Antipov** [comment]
Oh, right. Avalonia identifies user controls by URIs (which are derived from their filenames), and so do I for consistency purposes. The problem is I forgot that there are folks out there who use non-URI-friendly characters in their paths, such as spaces or even '#', like in your case (are those even allowed on Windows?). Will definitely implement a fix for these scenarios

**Comment by lxymahatma** [comment]
> Oh, right. Avalonia identifies user controls by URIs (which are derived from their filenames), and so do I for consistency purposes. The problem is I forgot that there are folks out there who use non-URI-friendly characters in their paths, such as spaces or even '#', like in your case (are those even allowed on Windows?). Will definitely implement a fix for these scenarios

yeah those are allowed on windows lol
idk if the method `Path.GetInvalidDirectoryName` exists but `Path.GetInvalidFileName` can be used to print all not allowed character for files. (tho there's no need to use the method here cz it's just reading directory name)

anyway thanks for the fix in advance 👍🏻

**Comment by Kir-Antipov** [comment]
Should be fixed in v1.0.1 :)
