### ISSUE TITLE
HotReloadDemo - hot reloading does not work in Visual Studio

### ISSUE THREAD

**Issue by toomasz** [Kir-Antipov/HotAvalonia#3]
1. Clone repository
2. Run HotReloadDemo in Debug mode
3. Demo opened succesfully
4. Changed main window title or button content 

Expected: Changes are reflected in view
Actual: No changes can be seen

I'm using Visual Studio 2022 - tried both .NET 7 and .NET 8

**Comment by Kir-Antipov** [comment]
Did you change the version of Avalonia?

Also, could you check please if everything works as expected on your machine with Visual Studio Code + C# Dev Kit extension? Technically, this setup uses the same debugger as Visual Studio, but I still need to rule out the possibility of the issue being Visual Studio-specific.

**Comment by Kir-Antipov** [comment]
That's quite interesting indeed. Maybe Visual Studio writes the changes to some temporary file before flushing it to the original one?

Also, I appreciate your help, as I cannot debug this on my end (don't have a Windows machine on my hands :D)

**Comment by Kir-Antipov** [comment]
Basically, to make HotAvalonia work with Visual Studio *(and any other code editor/IDE that uses the same file saving mechanics for that matter)* we need to teach [FileWatcher](https://github.com/Kir-Antipov/HotAvalonia/blob/master/src/HotAvalonia/IO/FileWatcher.cs) to report the series of events like this one:

```
- Deleted [File]
- Renamed [some-temporary-file] -> [File]
```

As a single `Changed` event for the `[File]` in question. Since the rename operation is guaranteed to happen last, i.e., after the original file was deleted, I think it's safe to add a heuristic for that here:

https://github.com/Kir-Antipov/HotAvalonia/blob/9b771556b1dfa11fb707e04039858c28c4b03dfb/src/HotAvalonia/IO/FileWatcher.cs#L206-L212

**Comment by toomasz** [comment]
Added PR, let me know if you agree with that solution
