### ISSUE TITLE
Multi-Project solution support

### ISSUE THREAD

**Issue by StefanKoell** [Kir-Antipov/HotAvalonia#7]
Hi!

I was wondering if there is a plan to support more complex solutions with multiple projects containing controls?

cheers,
Stefan

**Comment by StefanKoell** [comment]
Thanks for the quick response. I tried to make it work in my app but it doesn't do anything :( Need to dig further in when I have time. I would be happy with the ability to specify projects manually like you described. I'm wondering why hot reload isn't working for me at all. I guess there's no logging/tracing which can be enabled, right?

**Comment by StefanKoell** [comment]
@ClxS your solution works well for me. Thanks for sharing! @Kir-Antipov thanks again for all the help and the great work!

**Comment by Kir-Antipov** [comment]
> solution works well for me

That's great to hear! :)

However, I'm gonna leave this issue open, as it's something HotAvalonia needs to learn how to do out of the box.

**Comment by Epacik** [comment]
> So, yes, there are definitely plans to add proper support for referenced projects. The only thing that's missing here is establishing a relevance between a given referenced control assembly and its source project location. For instance, if you were to manually do something like this:
> 
> ```cs
> var context = AvaloniaHotReloadContext.FromAsembly(typeof(MyControl).Assembly, "/path/to/project/root/");
> context.EnableHotReload(); // Note: the context needs to be saved somewhere, so the GC doesn't throw it away.
> ```
> 
> It should already work. I just haven't found an elegant way to:
> 
> 1. Determine all referenced assemblies that contain Avalonia controls.
> 2. Find the project root for each of them.

It probably won't be *the* solution, but maybe it's possible to use a source generator to generate those contexts for referenced projects?

**Comment by Kir-Antipov** [comment]
While it's definitely *a* solution, it has its downsides. Namely:

1) For this approach to work, all projects containing Avalonia controls need to be explicitly referenced and accessible during compile time. However, this is not always the case. For example, ClxS mentioned that they use a plugin system that only kicks in during runtime, rendering source generators ineffective for them.

2) I'm not really sold on using source generators in such cases due to how high level they are. You either need to maintain 3 copies of the same source generators to support The Big Three *(i.e., C#, F#, and VB.NET)*, or go a different route like most .NET developers do and pretend that C# is the only .NET language, [which couldn't be further from the truth](https://en.wikipedia.org/wiki/List_of_CLI_languages). And, to be quite frankly honest with you, I don't want to do either of those.

Thus, I think I'm going to stick with the debug symbols-related solution.

**Comment by Epacik** [comment]
That makes sense.
May I ask how long would it take, to fix that problem properly, using debug symbols?

If it's going to take a longer while, I could volunteer some of my time to create some simple generators for The Big Three, and to keep them working.

Once you'd finish the debug symbols based solution, source generator could get deprecated and subsequently removed.

That would only make sense, if the solution you want to go with would take considerably longer to be made, hence my question.

**Comment by Kir-Antipov** [comment]
> how long would it take

In my better years, I could have done this in a day. However, without going into too much detail, I'm not in my most productive form at the moment, so it's more like a "will do it in an hour within a week" kind of deal.

Since this is going to be a breaking change anyways *(I need to abstract `AvaloniaHotReloadContext` so I can combine different contexts and support dynamic assembly loading)*, I'm going to tackle a bit more than just multi-project support. For example, I also want to implement support for asset hot reloading, which in turn requires a ~~better~~ different injection technique. My homebrewed one only supports injection into methods contained within assemblies built in the Debug mode; and for asset hot reloading, I would need to inject code into `Avalonia` itself, which has obviously been built with optimizations enabled, thus rendering my injection method irrelevant.

So, what I'm saying here is it will take some time, but not a lot, really.

> I could volunteer some of my time to create some simple generators for The Big Three

The sentiment is very much appreciated! However, it will definitely be faster for me to implement the solution I already settled on :)

**Comment by Epacik** [comment]
All right, in that case I will patiently wait!
And who knows, maybe I'll be able to help with something else down the line 😉

**Comment by Kir-Antipov** [comment]
@ClxS, does your plugin system load assemblies via `Assembly.Load(string path)` or `Assembly.Load(byte[] rawAssembly)`?

**Comment by Kir-Antipov** [comment]
On a slightly more generic note, I'm currently trying to think of a good way for users to provide location hints for their assemblies when it's really truly needed.

Within the current model, where hot reload is only enabled for a single project, it's easy - `.EnableHotReload()` accepts a path, which is usually provided by the compiler itself *(thanks to the `CallerFilePathAttribute`)*, but can be easily overridden by a user themselves:

```csharp
this.EnableHotReload("/path/to/control.cs");
```

However, a single string is not going to cut it in a multi-project setup. Any bright ideas, folks?

---

P.S. - by the way, everything else is already implemented, so I hope you will be able to at least test the new multi-project-oriented system in a few days when I'm done wiring up this last thing :)

**Comment by ClxS** [comment]
@Kir-Antipov at the moment I the strong path form

**Comment by Kir-Antipov** [comment]
@ClxS, that's great, actually, because assemblies loaded via `.Load(byte[])` do not have their `Location` property set, as they were loaded from the memory and not from the disk.

Since you use `.Load(string)`, the new `.EnableHotReload()` should work for you out of the box when I'm done!

**Comment by Kir-Antipov** [comment]
I think I'm done here. `.EnableHotReload()` should work out of the box now, even if you dynamically load assemblies into the current application domain.

If `HotAvalonia` cannot determine the location of some assembly's source project *(e.g., there are no debug symbols available, or projects are located in a different place compared to where they were when the assemblies were compiled, etc.)*, there's a new overload that lets you pass a callback function capable of resolving project paths:

```csharp
this.EnableHotReload(
  asm => TryLocateAssemblyProject(asm, out string? directoryName) ? directoryName : null
);
```

However, I genuinely think that you won't need that with your current setups.

Anyway, if you folks could test it on your end as well, it would be very much appreciated :)
You can wire your projects directly to the sources of the development branch, or grab pre-built binaries from [run#9329750366](https://github.com/Kir-Antipov/HotAvalonia/actions/runs/9329750366) and put them into a local NuGet repository *(which is just a fancy name for a directory mentioned in the `nuget.config`)*.

**Comment by toomasz** [comment]
Hey @Kir-Antipov , I have tested your changes on latest develomment branch related to app domain support and it works! Could you release HotAvalonia with those changes when you are free? Thanks

**Comment by Kir-Antipov** [comment]
Thanks! Yup, I'll get back to HotAvalonia shortly. I have just a few small-ish tasks to finish before the next release.

**Comment by Bodekaer** [comment]
@Kir-Antipov I'm testing the latest version 2.0.2 with a large multi-project. 
HotReload works for the main project, but none of the referenced projects. Any tips/advice on how to debug? 

Would it still make sense to try out the trick above?  (although the method is internal, so I'd need to replicate it).
```
this.EnableHotReload(
  asm => TryLocateAssemblyProject(asm, out string? directoryName) ? directoryName : null
);
```

Any tips most welcome :)

**Comment by Kir-Antipov** [comment]
Please check the debug window and review the logs printed by HotAvalonia. What do they say? If HotAvalonia has identified the referenced assemblies as Avalonia projects but couldn't locate their original locations, then yup, you could resolve this issue using a custom project locator.

>  (although the method is internal, so I'd need to replicate it).

The `TryLocateAssemblyProject` method is not internal - it simply doesn't exist. You'll need to implement this logic yourself to enable HotAvalonia to match assemblies containing Avalonia controls with their source project locations.

That said, I'd be interested to learn more about your situation and why HotAvalonia isn't working for referenced projects in your case. *(Are debug symbols available for those?)* However, it might be better to open a new issue to discuss this further, so we don't ping other folks subscribed to this thread.
